const SECURITY_PROFILES={
 attorney:{id:'attorney-demo',name:'Avery Chen',role:'Lead attorney',permissions:['case_view','privileged_work_product','ai_use','drafting','authority_research','communications_client','communications_team','review_decisions','audit_view','export','security_admin']},
 cocounsel:{id:'cocounsel-demo',name:'Priya Shah',role:'Co-counsel',permissions:['case_view','privileged_work_product','ai_use','drafting','authority_research','communications_client','communications_team','review_decisions','audit_view','export']},
 investigator:{id:'investigator-demo',name:'Luis Reyes',role:'Investigator',permissions:['case_view','ai_use','communications_team','audit_view']},
 client:{id:'client-demo',name:'Jordan Hale',role:'Client',permissions:['case_view','communications_client']}
};
let activeSecurityProfile=sessionStorage.getItem('casebrief_demo_role')||'attorney';
let privacyMode=false,sessionLocked=false,lastActivityAt=Date.now();
const SESSION_IDLE_MS=15*60*1000;
function currentIdentity(){const p=SECURITY_PROFILES[activeSecurityProfile]||SECURITY_PROFILES.attorney;return {id:p.id,name:p.name,type:'human',role:p.role,verified:false}}
function currentProfile(){return SECURITY_PROFILES[activeSecurityProfile]||SECURITY_PROFILES.attorney}
function can(permission){return currentProfile().permissions.includes(permission)}
function documentClassification(d){if(!d)return 'restricted';if(d.type==='Attorney note')return 'privileged';if(['Witness statement','Police report','Evidence log','Transcript','Correspondence'].includes(d.type))return 'confidential';return 'case-record'}
function canAccessDocument(d){const cls=documentClassification(d);if(cls==='privileged'&&!can('privileged_work_product'))return false;return can('case_view')}
function permittedSourceIds(ids=[]){return ids.filter(id=>canAccessDocument(data.documents.find(d=>d.id===id)))}
function securityDenied(permission,target){if(typeof record==='function')record('security.access_denied',target,{permission,role:currentProfile().role},'denied',currentIdentity());showSecurityNotice(`Access denied for ${currentProfile().role}. This action requires ${permission.replaceAll('_',' ')} permission.`);return false}
function requirePermission(permission,target='action'){return can(permission)||securityDenied(permission,target)}
function showSecurityNotice(message){let el=document.getElementById('securityToast');if(!el){el=document.createElement('div');el.id='securityToast';el.className='security-toast';document.body.appendChild(el)}el.textContent=message;el.hidden=false;clearTimeout(el._timer);el._timer=setTimeout(()=>el.hidden=true,4200)}
function switchSecurityProfile(key){if(!SECURITY_PROFILES[key])return;const from=activeSecurityProfile;activeSecurityProfile=key;sessionStorage.setItem('casebrief_demo_role',key);if(typeof record==='function')record('security.role_demo_changed',key,{from,to:key,clientSideDemo:true},'success',currentIdentity());applySecurityUI();if(typeof nav==='function')nav();if(typeof render==='function')render()}
function securityRoleControl(){return `<label class="security-role">Demo role<select id="securityRole" onchange="switchSecurityProfile(this.value)">${Object.entries(SECURITY_PROFILES).map(([k,p])=>`<option value="${k}" ${k===activeSecurityProfile?'selected':''}>${esc(p.role)}</option>`).join('')}</select></label>`}
function applySecurityUI(){document.body.classList.toggle('privacy-mode',privacyMode);document.body.classList.toggle('session-locked',sessionLocked);const badge=document.getElementById('securityStateBadge');if(badge)badge.textContent=sessionLocked?'Locked':privacyMode?'Privacy mode':'Protected demo'}
function togglePrivacyMode(){privacyMode=!privacyMode;record('security.privacy_mode_changed','session',{enabled:privacyMode},'success',currentIdentity());applySecurityUI();syncPrivacyShield()}
function syncPrivacyShield(){let shield=document.getElementById('privacyShield');if(!shield){shield=document.createElement('div');shield.id='privacyShield';shield.className='privacy-shield';shield.innerHTML='<div><div class="shield-icon">◉</div><h2>Privacy mode</h2><p>Case content is concealed on this screen.</p><button class="btn primary" onclick="togglePrivacyMode()">Reveal workspace</button></div>';document.body.appendChild(shield)}shield.hidden=!privacyMode}
function lockSession(reason='manual'){sessionLocked=true;record('security.session_locked','session',{reason},'success',currentIdentity());applySecurityUI();syncLockScreen()}
function unlockSession(){sessionLocked=false;lastActivityAt=Date.now();record('security.session_unlocked','session',{clientSideDemo:true},'success',currentIdentity());applySecurityUI();syncLockScreen()}
function syncLockScreen(){let el=document.getElementById('sessionLock');if(!el){el=document.createElement('div');el.id='sessionLock';el.className='session-lock';el.innerHTML=`<div class="lock-card"><div class="shield-icon">◆</div><h2>CaseBrief session locked</h2><p>Protected case content is hidden until identity is re-verified.</p><div class="callout small"><b>MVP note:</b> this demonstrates session-lock behaviour. Production unlock requires authenticated re-verification/MFA or a passkey.</div><button class="btn primary" onclick="unlockSession()">Re-verify demo session</button></div>`;document.body.appendChild(el)}el.hidden=!sessionLocked}
function noteActivity(){lastActivityAt=Date.now()}
setInterval(()=>{if(!sessionLocked&&Date.now()-lastActivityAt>SESSION_IDLE_MS)lockSession('idle_timeout')},30000);
document.addEventListener('pointerdown',noteActivity,{passive:true});document.addEventListener('keydown',noteActivity);
function guardedView(permission,view){if(!requirePermission(permission,`view:${view}`))return;showView(view)}
function confirmSensitiveAction(kind,description,onConfirm){returnFocus=document.activeElement;record('security.sensitive_action_prompted',kind,{description});document.getElementById('detailRoot').innerHTML=`<div class="drawerback"><aside class="drawer" role="dialog" aria-modal="true" aria-labelledby="sensitiveTitle"><div class="drawerhead"><div><div class="kicker">Sensitive action confirmation</div><h2 id="sensitiveTitle">Confirm ${esc(kind)}</h2></div><button class="btn drawerclose" onclick="closeDetail()">×</button></div><p>${esc(description)}</p><div class="callout"><b>Security check:</b> this action will be recorded in the matter audit trail with the active identity, target, time, and outcome.</div><div class="row" style="margin-top:16px"><button id="confirmSensitive" class="btn primary">Confirm action</button><button class="btn" onclick="closeDetail()">Cancel</button></div></aside></div>`;document.getElementById('confirmSensitive').onclick=()=>{record('security.sensitive_action_confirmed',kind,{description});closeDetail();onConfirm()};document.getElementById('confirmSensitive').focus()}
function securityCenter(){const p=currentProfile();const perms=['case_view','privileged_work_product','ai_use','drafting','authority_research','communications_client','communications_team','review_decisions','audit_view','export','security_admin'];return `<div class="kicker">Security & trust center</div><div class="row" style="justify-content:space-between"><div><h2>Security Center</h2><p class="muted">Interactive MVP controls plus the production security contract.</p></div><span class="security-badge" id="securityStateBadge">Protected demo</span></div><div class="security-banner"><b>Active identity:</b> ${esc(p.name)} · ${esc(p.role)} <span class="pill medium">demo identity — not server verified</span></div><div class="grid"><div class="card c6"><h3>Controls you can demonstrate now</h3><div class="security-actions"><button class="btn" onclick="togglePrivacyMode()">${privacyMode?'Disable':'Enable'} privacy mode</button><button class="btn" onclick="lockSession('manual')">Lock session</button></div><ul><li>Role/matter permission checks before protected views and actions</li><li>Privileged attorney notes blocked from non-privileged roles</li><li>AI source retrieval filtered through the active role</li><li>Automatic 15-minute idle lock</li><li>Explicit confirmation for sensitive exports</li><li>Security denials and role changes written to activity history</li><li>Content escaped before rendering to reduce script-injection risk</li><li>Referrer and browser capability restrictions in the demo page</li></ul></div><div class="card c6"><h3>Current role permissions</h3><div class="permission-grid">${perms.map(x=>`<div class="permission ${can(x)?'allowed':'denied'}"><span>${can(x)?'✓':'×'}</span>${esc(x.replaceAll('_',' '))}</div>`).join('')}</div></div><div class="card c12"><h3>Production security gates — required before real client data</h3><div class="security-columns"><ul><li>Server-enforced authentication and authorization</li><li>MFA/passkeys and enterprise SSO</li><li>Secure account recovery and device/session revocation</li><li>Encryption in transit and at rest with managed keys</li><li>Tenant and matter isolation enforced server-side</li><li>Append-only/tamper-evident audit storage</li></ul><ul><li>Secure messaging delivery infrastructure</li><li>Malware scanning and attachment validation</li><li>Data retention, legal hold, deletion and export controls</li><li>Secrets management, monitoring, backup and incident response</li><li>Vendor/model data-processing controls and no-training commitments</li><li>Independent security review and penetration testing</li></ul></div><p class="callout notice"><b>Important:</b> client-side controls can demonstrate product behaviour but cannot secure a public static site against a determined user with browser developer tools. Production protections must be enforced by the backend.</p></div></div>`}
