function umg(){return `<div class="kicker">UMG integration boundary</div><h2>UMG Runtime / Analysis Trace</h2><p class="callout"><b>Current MVP state:</b> the workflow and audit surfaces are present, but the assistant on this page is simulated. A live model/document/research path should run through the agreed CaseBrief ↔ UMG contract rather than pretending the connector is already live.</p><div class="grid"><div class="card c6"><h3>Record Consistency Review</h3><p class="muted">Run the deterministic fixture to surface seeded contradictions and record gaps.</p><button class="btn primary" onclick="runConsistency()">Run sandbox review</button><div id="runner"></div></div><div class="card c6"><h3>Expected live tool path</h3><pre>CaseBrief matter state
↓
UMG compile / Sleeve
↓
Needs + ToolRequests
↓
CaseBrief document / research / model tools
↓
ToolResults + state update
↓
Trace + audit event</pre></div><div class="card c12"><h3>New surfaces that must be wired through the integration</h3><div class="row"><span class="pill">AI chat</span><span class="pill">authority research</span><span class="pill">document drafting</span><span class="pill">rights flags</span><span class="pill">source citations</span><span class="pill">audit events</span></div></div></div>`}
function runConsistency(){if(!applicationAllowed())return blockApplication();const hits=data.issues.filter(x=>['contradiction','missing_evidence','timeline_gap','unsupported_assertion'].includes(x.category));record('analysis.started','record-consistency',{simulated:true});document.getElementById('runner').innerHTML=`<div class="list" style="margin-top:10px">${hits.map(x=>`<div class="item"><b>${esc(x.category)}</b><div>${esc(x.statement)}</div><div class="meta">${esc(x.sources.join(', '))}</div></div>`).join('')}</div>`;record('analysis.completed','record-consistency',{findings:hits.map(x=>x.id),simulated:true},'success',systemActor)}

const AUDIT_ACTION_LABELS={
 'session.started':'Session started','view.opened':'Page opened','control.activated':'Control selected','case.switched':'Active case changed',
 'record.opened':'Record opened','detail.closed':'Details closed','cri.opened':'CRI details opened','review.decision_started':'Review decision started',
 'issue.status_changed':'Review status changed','document.review_changed':'Document review changed','authority.verification_changed':'Authority verification changed',
 'ai.question_asked':'Question asked','ai.response_generated':'AI response generated','ai.chat_cleared':'AI chat cleared','draft.generated':'Draft generated',
 'draft.opened':'Draft opened','draft.edit_started':'Document editing started','draft.version_saved':'Document version saved','content.copied':'Content copied','content.copy_failed':'Copy failed','communication.compose_opened':'Message draft opened',
 'communication.content_prepared':'Message prepared','communication.demo_recorded':'Demo message recorded','analysis.started':'Analysis started',
 'analysis.completed':'Analysis completed','security.profile_changed':'Active role changed','security.role_demo_changed':'Active role changed','security.access_denied':'Access denied',
 'security.privacy_enabled':'Privacy mode enabled','security.privacy_disabled':'Privacy mode disabled','security.privacy_mode_changed':'Privacy mode changed','security.session_locked':'Session locked',
 'security.session_unlocked':'Session unlocked','security.controls_initialized':'Security controls initialized','security.sensitive_action_prompted':'Sensitive action confirmation requested',
 'security.sensitive_action_confirmed':'Sensitive action confirmed','security.sensitive_action_cancelled':'Sensitive action cancelled','data.egress_attempt':'External copy/export attempted',
 'audit.export_requested':'Activity export requested','audit.export_confirmed':'Activity export confirmed','survey.saved':'Survey response saved'
};
const AUDIT_FIELD_LABELS={after:'New value',before:'Previous value',blockedSourceCount:'Restricted sources withheld',categoryTotals:'CRI reductions by category',chars:'Content length',classification:'Classification',clientSideDemo:'Demo-only control',contentExcluded:'Sensitive content excluded',contentExcludedFromAudit:'Sensitive content excluded',criAfter:'CRI after',criBefore:'CRI before',currentChars:'Current character count',findings:'Findings',from:'From',idleLockMinutes:'Automatic lock',mode:'Workspace mode',previousChars:'Previous character count',promptChars:'Question length',reason:'Reason',requestedStatus:'Requested status',responseContentExcluded:'Response content excluded',role:'Role',score:'CRI score',simulated:'Simulated result',sourceIds:'Sources used',sourceMatter:'Source matter',sources:'Sources',title:'Title',to:'To',type:'Type',version:'Saved version'};
function auditWords(value){return String(value??'').replaceAll('_',' ').replaceAll('.',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function auditActionLabel(action){return AUDIT_ACTION_LABELS[action]||auditWords(action)}
function auditTargetName(id){if(!id)return '';if(id===data.matter.id)return data.matter.title;const groups=[['documents','title'],['drafts','title'],['authorities','title'],['evidence','name'],['witnesses','name'],['timeline','text'],['issues','statement'],['contacts','name'],['messages','subject']];for(const [group,label] of groups){const item=data[group]?.find(x=>x.id===id);if(item?.[label])return item[label]}return auditWords(id)}
function auditTargetLabel(target){const raw=String(target??'');const [kind,...rest]=raw.split(':'),id=rest.join(':');const labels={ai:'AI workspace',assistant:'AI assistant',audit:'Activity history',authorities:'Law & authority',case:'Case',clipboard:'Clipboard',communications:'Communications',communication:'Communication',dashboard:'Case overview',document:'Document',documents:'Documents',draft:'Draft',drafting:'Drafting Studio',evidence:'Evidence',issue:'Review item',landing:'Public view',record:'Record',review:'Review Queue',safeguards:'Safeguards',security:'Security Center',session:'Session',survey:'Attorney Survey',timeline:'Court & chronology',umg:'UMG Runtime',view:'Page',witnesses:'Witnesses'};return id?`${labels[kind]||auditWords(kind)}: ${auditTargetName(id)}`:(labels[raw]||auditTargetName(raw)||'Not specified')}
function auditValue(key,value){
 if(value===true)return key==='simulated'?'Yes — prototype simulation':'Yes';
 if(value===false)return 'No';
 if(value===null||value===undefined||value==='')return 'Not recorded';
 if(Array.isArray(value))return value.length?value.map(v=>auditTargetLabel(v)).join(', '):'None';
 if(typeof value==='object')return Object.entries(value).map(([k,v])=>`${auditWords(k)}: ${auditValue(k,v)}`).join(' · ');
 if(key==='chars'||key==='promptChars')return `${value} characters`;
 if(key==='idleLockMinutes')return `${value} minutes`;
 if(key==='score'||key==='criBefore'||key==='criAfter')return `${value}%`;
 if(['after','before','requestedStatus','role','type'].includes(key))return auditWords(value);
 return String(value);
}
function auditContext(details={}){const rows=Object.entries(details);if(!rows.length)return '<span class="muted small">No additional context</span>';return `<div class="audit-context">${rows.map(([key,value])=>`<div class="audit-field"><span>${esc(AUDIT_FIELD_LABELS[key]||auditWords(key))}</span><b>${esc(auditValue(key,value))}</b></div>`).join('')}</div><details class="audit-technical"><summary>View technical details</summary><pre>${esc(JSON.stringify(details,null,2))}</pre></details>`}
function activityHistory(){const events=workspace.events.filter(e=>e.matterId===data.matter.id),visible=events.slice(-100);return `<div class="kicker">Traceable activity</div><div class="row" style="justify-content:space-between"><div><h2>Activity history</h2><p class="muted">Human and system actions share one matter-level trace in clear, reviewable language.</p>${events.length>visible.length?`<p class="small muted">Showing the newest ${visible.length} of ${events.length} entries. The technical export includes all entries.</p>`:''}</div><button class="btn" onclick="exportActivity()">Export technical record</button></div><p class="callout notice">Prototype activity is browser-local and not tamper-proof. Production requires authenticated identities, append-only server-side audit storage, access controls, monitoring, retention rules, and integrity protections.</p><div class="tablewrap"><table class="audit-table"><thead><tr><th>When</th><th>Who</th><th>Action</th><th>Target</th><th>Context</th></tr></thead><tbody>${visible.slice().reverse().map(e=>`<tr><td data-label="When" class="nowrap">${fmtDate(e.at)}</td><td data-label="Who">${esc(e.actor.name)}<div class="muted small">${esc(auditWords(e.actor.type))}</div></td><td data-label="Action"><b>${esc(auditActionLabel(e.action))}</b><div class="pill ${e.outcome==='success'?'low':'high'}">${esc(auditWords(e.outcome||'success'))}</div></td><td data-label="Target">${esc(auditTargetLabel(e.target))}</td><td data-label="Context">${auditContext(e.details)}</td></tr>`).join('')||'<tr><td colspan="5" class="muted">No activity has been recorded for this matter.</td></tr>'}</tbody></table></div>`}
function exportActivity(){record('audit.export_requested',data.matter.id);const payload={notice:'Unverified browser-local prototype history',matterId:data.matter.id,events:workspace.events.filter(e=>e.matterId===data.matter.id)};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`casebrief-${data.matter.id}-activity.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);render()}
function safeguards(){return `<div class="kicker">Trust architecture</div><h2>Safeguards and product boundaries</h2><div class="grid"><div class="card c6"><h3>Prototype safeguards visible now</h3><ul><li>Matter-level activity history</li><li>Human review status and required decision reasons</li><li>Source-linked findings</li><li>Explicit simulated-AI labels</li><li>Attorney-verification state for authority</li><li>Drafts marked for attorney review</li><li>Communications marked as demo/not transmitted</li></ul></div><div class="card c6"><h3>Production security still required</h3><ul><li>Authenticated identities + MFA</li><li>Role-based and matter-based access</li><li>Encryption in transit and at rest</li><li>Append-only/tamper-evident auditing</li><li>Secure client messaging infrastructure</li><li>Retention and legal-hold controls</li><li>Secrets/key management</li><li>Backups, monitoring, incident response</li><li>Vendor/model data-handling controls</li></ul></div><div class="card c12"><h3>Control principle</h3><p class="metric" style="font-size:24px">AI identifies. Human decides. The system records both.</p></div></div>`}
function survey(){return `<div class="kicker">Product research</div><h2>Attorney workflow validation</h2><p class="muted">3–5 minute research survey. This is not legal intake.</p><form onsubmit="submitSurvey(event)"><label for="surveyRole">Role</label><select id="surveyRole" name="role"><option>Public defender</option><option>Private criminal defense</option><option>Prosecutor</option><option>Appellate attorney</option><option>Other</option></select><label for="surveyPractice">Practice area</label><input id="surveyPractice" name="practice"><label for="surveySize">Firm / office size</label><input id="surveySize" name="size"><label for="surveyYears">Years of experience</label><input id="surveyYears" name="years" inputmode="numeric"><label for="surveyTime">Where does case-review time disappear?</label><textarea id="surveyTime" name="time"></textarea><label for="surveyMissed">What repeatedly gets missed or found late?</label><textarea id="surveyMissed" name="missed"></textarea><label for="surveyTop">Which CaseBrief capabilities would matter most?</label><textarea id="surveyTop" name="top"></textarea><button class="btn primary">Save demo response</button></form><div id="surveyMsg" role="status" aria-live="polite"></div>`}
function submitSurvey(e){e.preventDefault();const vals=Object.fromEntries(new FormData(e.target));const arr=JSON.parse(localStorage.getItem('casebrief_survey')||'[]');arr.push(vals);localStorage.setItem('casebrief_survey',JSON.stringify(arr));record('survey.saved','attorney-survey',{responseContentExcluded:true});document.getElementById('surveyMsg').innerHTML='<p class="callout">Saved locally in this browser.</p>';e.target.reset()}
