function landing(){return `<section class="hero"><div class="kicker">Legal case intelligence with traceable human control</div><h1>See the case. Ask the case. Act on the case.</h1><p>CaseBrief connects records, chronology, evidence, people, law, AI-assisted review, drafting, communications, and audit history in one inspectable matter workspace.</p><div class="row"><button class="btn primary" onclick="showView('dashboard')">Open demo workspace</button><button class="btn" onclick="showView('assistant')">Try case AI</button></div></section><div class="grid" style="margin-top:14px"><div class="card c4"><div class="kicker">Glanceable</div><h3>Readiness + court posture</h3><p class="muted">CRI shows what is holding review back while a separate procedural timeline shows where the matter sits in court.</p></div><div class="card c4"><div class="kicker">Actionable</div><h3>Ask, draft, communicate</h3><p class="muted">Move directly from source-grounded questions to attorney-reviewed work product and client/team communication.</p></div><div class="card c4"><div class="kicker">Inspectable</div><h3>Sources, authority, audit</h3><p class="muted">Every important action leaves a trail, and legal research remains visibly subject to attorney verification.</p></div></div>`}

function dashboard(){
 if(data.matter.id==='matter-002')return `<div class="kicker">Synthetic intake matter</div><h2>${esc(data.matter.title)}</h2><p>${esc(data.matter.number)} · ${esc(data.matter.stage)}</p>${courtProgress(true)}<div class="grid" style="margin-top:14px"><div class="card c6"><h3>CRI pending</h3><p class="muted">No records have been added. Readiness cannot be assessed yet.</p><button class="btn" onclick="showView('documents')">Open document library</button></div><div class="card c6"><h3>Start working</h3><div class="row"><button class="btn" onclick="showView('assistant')">Ask CaseBrief AI</button><button class="btn" onclick="showView('communications')">Contact client</button></div></div></div>`;
 const s=score(),open=data.issues.filter(isUnresolved).length,rights=data.issues.filter(x=>x.category==='potential_rights_violation'&&isUnresolved(x)).length;
 return `<div class="kicker">Case command centre · synthetic historical fixture</div><div class="row" style="justify-content:space-between;align-items:flex-start"><div><h2 style="margin-bottom:5px"><button class="linkbtn" onclick="openDetail('matter','${data.matter.id}')">${esc(data.matter.title)}</button></h2><p class="muted" style="margin-top:0">${esc(data.matter.number)} • ${esc(data.matter.stage)} • Attorney: <button class="linkbtn" onclick="openDetail('person','attorney')">${esc(data.matter.attorney)}</button></p></div><div class="row"><button class="btn primary" onclick="showView('assistant')">Ask AI</button><button class="btn" onclick="showView('drafting')">Draft document</button><button class="btn" onclick="showView('communications')">Message client/team</button></div></div>
 <div class="card" style="margin-bottom:14px"><div class="row" style="justify-content:space-between"><div><div class="kicker">Court process</div><h3 style="margin-bottom:6px">Where this case is now</h3></div><button class="btn sm" onclick="showView('timeline')">Open full timeline</button></div>${courtProgress(true)}</div>
 <div class="grid">
  <div class="card c5"><div class="orbwrap"><button class="orb" aria-label="Open ${s}% Case Readiness Index details" style="--pct:${s}" onclick="openCRI()"><span class="orbscore">${s}%<small>CRI</small></span><span class="crihover"><span class="crihoverhead">Factors reducing CRI</span>${factorSummary(false)}<span class="crihoverfoot">Hover = category totals • Click = full detail</span></span></button><div><div class="kicker">Case Readiness Index</div><div class="metric">${s}%</div><div class="muted">${open} unresolved review items</div>${rights?`<div class="pill high" style="margin-top:8px">${rights} rights flag${rights===1?'':'s'} for attorney review</div>`:''}<div class="hint">Click the ring for deeper factor detail →</div></div></div><p class="muted">Readiness/workload indicator only. It does not predict merit, guilt, innocence, or outcome.</p></div>
  <div class="card c3 clickable" tabindex="0" onclick="openDetail('deadline')"><div class="kicker">Next deadline</div><div class="metric">Aug 26</div><div class="muted">Motions due</div><div class="hint">Open deadline source →</div></div>
  <div class="card c4"><div class="kicker">CaseBrief AI</div><h3>Ask the case, not a generic chatbot</h3><p class="muted">Questions stay scoped to matter records and source trails in this prototype.</p><div class="row"><button class="btn primary" onclick="showView('assistant')">Open AI chat</button><button class="btn" onclick="quickAsk('What needs attention next?')">Ask what needs attention</button></div></div>
  <div class="card c7"><div class="row" style="justify-content:space-between"><div><div class="kicker">Law & authority</div><h3>Potentially relevant research</h3></div><button class="btn sm" onclick="showView('authorities')">Research hub</button></div><p class="muted">Case-linked authority is surfaced for attorney verification — not silently treated as controlling law.</p><div class="list">${data.authorities.slice(0,3).map(a=>`<div class="item clickable" tabindex="0" onclick="openDetail('authority','${a.id}')"><b>${esc(a.title)}</b> <span class="pill">${esc(a.status)}</span><div>${esc(a.topic)}</div><div class="meta">${esc(a.cite)} • inspect relevance →</div></div>`).join('')}</div></div>
  <div class="card c5"><div class="kicker">Work tools</div><h3>From review to action</h3><div class="list"><div class="item clickable" tabindex="0" onclick="showView('drafting')"><b>Drafting Studio</b><div class="muted">Create formatted case memo, discovery follow-up, client update, or motion outline.</div></div><div class="item clickable" tabindex="0" onclick="showView('communications')"><b>Communications</b><div class="muted">Secure-client/team workflow mock with a matter-linked message history.</div></div><div class="item clickable" tabindex="0" onclick="showView('audit')"><b>Activity history</b><div class="muted">Review who did what, when, and in which case.</div></div></div></div>
  <div class="card c7"><h3>Factors affecting case readiness</h3><p class="muted">Open items reducing CRI. Select a factor for sources, reasoning context, and status controls.</p>${data.issues.filter(isUnresolved).slice(0,5).map(x=>`<div class="item clickable" tabindex="0" onclick="openDetail('issue','${x.id}')"><span class="pill ${x.severity}">${x.severity}</span><b>${esc(x.category.replaceAll('_',' '))}</b><div class="muted">${esc(x.statement)}</div><div class="meta">−${x.weight}% while unresolved • inspect →</div></div>`).join('')}<button class="btn" style="margin-top:12px" onclick="showView('review')">View all ${open} factors</button></div>
  <div class="card c5"><h3>Recent matter activity</h3><div class="list">${workspace.events.filter(e=>e.matterId===data.matter.id).slice(-4).reverse().map(e=>`<div class="item"><b>${esc(e.action)}</b><div class="muted">${esc(e.target)}</div><div class="meta">${fmtDate(e.at)} • ${esc(e.actor.name)}</div></div>`).join('')||'<div class="muted">No activity recorded yet.</div>'}</div></div>
 </div>`;
}

function review(){return `<div class="kicker">Human review queue</div><h2>Potential issues requiring attorney review</h2><p class="callout"><b>AI identifies. Human decides.</b> Findings remain source-linked review prompts until a human reviewer records a disposition and reason.</p><div class="list">${data.issues.map(x=>`<div class="item ${!isUnresolved(x)?'resolved':''}"><div><span class="pill ${x.severity}">${esc(x.severity)}</span><span class="pill">${esc(x.category)}</span><span class="pill">${esc(x.status)}</span></div><h3>${esc(x.statement)}</h3><p class="muted">${esc(x.why)}</p><div>${srcChips(x.sources)}</div><div class="row" style="margin-top:10px">${isUnresolved(x)?`<button class="btn good" onclick="beginIssueDecision('${x.id}','resolved')">Resolve</button><button class="btn" onclick="beginIssueDecision('${x.id}','reviewed')">Mark reviewed</button><button class="btn bad" onclick="beginIssueDecision('${x.id}','dismissed')">Dismiss</button>`:`<button class="btn" onclick="beginIssueDecision('${x.id}','open')">Reopen</button>`}<button class="btn ghost" onclick="openDetail('issue','${x.id}')">Inspect detail</button></div></div>`).join('')||'<p class="muted">No review items.</p>'}</div>`}

function timeline(){return `<div class="kicker">Procedure + source-supported chronology</div><h2>Where the case is in court</h2><p class="muted">This procedural track is intentionally separate from the factual/evidentiary chronology below.</p>${courtProgress(false)}<div style="height:18px"></div><div class="row" style="justify-content:space-between"><div><div class="kicker">Case chronology</div><h2>What happened and when</h2></div></div><div class="list">${data.timeline.map(t=>`<div class="item clickable" tabindex="0" onclick="openDetail('timeline','${t.id}')"><span class="pill">${esc(t.kind.replaceAll('_',' '))}</span><b>${esc(t.time)}</b><p>${esc(t.text)}</p>${srcChips(t.sources)}<div class="hint">Inspect event →</div></div>`).join('')||'<p class="muted">No chronology events have been added.</p>'}</div>`}
function evidence(){return `<div class="kicker">Evidence hub</div><h2>Evidence</h2><div class="grid">${data.evidence.map(e=>`<div class="card c6 clickable" tabindex="0" onclick="openDetail('evidence','${e.id}')"><h3>${esc(e.name)}</h3><span class="pill ${e.status.includes('missing')?'high':'low'}">${esc(e.status)}</span><p class="muted">${e.related.length} related source record${e.related.length===1?'':'s'}</p><div class="hint">Inspect evidence record →</div></div>`).join('')||'<div class="card c12"><p class="muted">No evidence records have been added.</p></div>'}</div>`}
function witnesses(){return `<div class="kicker">Witness hub</div><h2>Witnesses & consistency flags</h2><div class="grid">${data.witnesses.map(w=>`<div class="card c6 clickable" tabindex="0" onclick="openDetail('witness','${w.id}')"><h3>${esc(w.name)}</h3><div class="muted">${esc(w.role)}</div><p>${esc(w.statement)}</p><b>${w.flags.length} consistency flag${w.flags.length===1?'':'s'}</b><p class="muted">No credibility or truth score is assigned.</p><div class="hint">Open witness profile →</div></div>`).join('')||'<div class="card c12"><p class="muted">No witnesses have been added.</p></div>'}</div>`}
function documents(){return `<div class="kicker">Document library</div><div class="row" style="justify-content:space-between"><h2>Case documents</h2><button class="btn" onclick="showView('drafting')">Create case document</button></div><div class="tablewrap"><table><thead><tr><th>Document</th><th>Type</th><th>Date</th><th>Status</th></tr></thead><tbody>${data.documents.map(d=>`<tr class="clickable" tabindex="0" onclick="openDetail('document','${d.id}')"><td><button class="linkbtn">${esc(d.title)}</button><div class="muted">${esc(d.excerpt)}</div><div class="hint">Open indexed document →</div></td><td>${esc(d.type)}</td><td>${esc(d.date)}</td><td><span class="pill ${d.reviewed?'low':'medium'}">${d.reviewed?'Reviewed':'Unreviewed'}</span></td></tr>`).join('')||'<tr><td colspan="4" class="muted">No documents have been added.</td></tr>'}</tbody></table></div>`}

function authorities(){return `<div class="kicker">Relevant law & research</div><div class="row" style="justify-content:space-between"><div><h2>Case-linked authority</h2><p class="muted">Potentially relevant law is tied to issues and remains explicitly subject to attorney verification.</p></div><button class="btn" onclick="quickAsk('What legal issues need more research?')">Ask AI for research gaps</button></div><div class="grid">${data.authorities.map(a=>`<div class="card c6 clickable" tabindex="0" onclick="openDetail('authority','${a.id}')"><div class="row"><span class="pill">${esc(a.status)}</span>${a.verified?'<span class="pill low">verified</span>':'<span class="pill medium">attorney verification needed</span>'}</div><h3>${esc(a.title)}</h3><b>${esc(a.cite)}</b><p>${esc(a.topic)}</p><p class="muted">${esc(a.note)}</p><div class="hint">Inspect links to case issues →</div></div>`).join('')||'<div class="card c12"><p class="muted">No authorities have been linked yet.</p></div>'}</div>`}

