function umg(){return `<div class="kicker">UMG integration boundary</div><h2>UMG Runtime / Analysis Trace</h2><p class="callout"><b>Current MVP state:</b> the workflow and audit surfaces are present, but the assistant on this page is simulated. A live model/document/research path should run through the agreed CaseBrief ↔ UMG contract rather than pretending the connector is already live.</p><div class="grid"><div class="card c6"><h3>Record Consistency Review</h3><p class="muted">Run the deterministic fixture to surface seeded contradictions and record gaps.</p><button class="btn primary" onclick="runConsistency()">Run sandbox review</button><div id="runner"></div></div><div class="card c6"><h3>Expected live tool path</h3><pre>CaseBrief matter state
↓
UMG compile / Sleeve
↓
Needs + ToolRequests
↓
CaseBrief document / research / model tools
↓
ToolResults + state update
↓
Trace + audit event</pre></div><div class="card c12"><h3>New surfaces that must be wired through the integration</h3><div class="row"><span class="pill">AI chat</span><span class="pill">authority research</span><span class="pill">document drafting</span><span class="pill">rights flags</span><span class="pill">source citations</span><span class="pill">audit events</span></div></div></div>`}
function runConsistency(){const hits=data.issues.filter(x=>['contradiction','missing_evidence','timeline_gap','unsupported_assertion'].includes(x.category));record('analysis.started','record-consistency',{simulated:true});document.getElementById('runner').innerHTML=`<div class="list" style="margin-top:10px">${hits.map(x=>`<div class="item"><b>${esc(x.category)}</b><div>${esc(x.statement)}</div><div class="meta">${esc(x.sources.join(', '))}</div></div>`).join('')}</div>`;record('analysis.completed','record-consistency',{findings:hits.map(x=>x.id),simulated:true},'success',systemActor)}

function activityHistory(){const events=workspace.events.filter(e=>e.matterId===data.matter.id);return `<div class="kicker">Traceable activity</div><div class="row" style="justify-content:space-between"><div><h2>Activity history</h2><p class="muted">Human and system actions share one matter-level trace.</p></div><button class="btn" onclick="exportActivity()">Export activity JSON</button></div><p class="callout notice">Prototype activity is browser-local and not tamper-proof. Production requires authenticated identities, append-only server-side audit storage, access controls, monitoring, retention rules, and integrity protections.</p><div class="tablewrap"><table><thead><tr><th>When</th><th>Who</th><th>Action</th><th>Target</th><th>Context</th></tr></thead><tbody>${events.slice().reverse().map(e=>`<tr><td>${fmtDate(e.at)}</td><td>${esc(e.actor.name)}<div class="muted small">${esc(e.actor.type)}</div></td><td>${esc(e.action)}</td><td>${esc(e.target)}</td><td><pre>${esc(JSON.stringify(e.details,null,2))}</pre></td></tr>`).join('')||'<tr><td colspan="5" class="muted">No events yet.</td></tr>'}</tbody></table></div>`}
function exportActivity(){record('audit.export_requested',data.matter.id);const payload={notice:'Unverified browser-local prototype history',matterId:data.matter.id,events:workspace.events.filter(e=>e.matterId===data.matter.id)};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`casebrief-${data.matter.id}-activity.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);render()}
function safeguards(){return `<div class="kicker">Trust architecture</div><h2>Safeguards and product boundaries</h2><div class="grid"><div class="card c6"><h3>Prototype safeguards visible now</h3><ul><li>Matter-level activity history</li><li>Human review status and required decision reasons</li><li>Source-linked findings</li><li>Explicit simulated-AI labels</li><li>Attorney-verification state for authority</li><li>Drafts marked for attorney review</li><li>Communications marked as demo/not transmitted</li></ul></div><div class="card c6"><h3>Production security still required</h3><ul><li>Authenticated identities + MFA</li><li>Role-based and matter-based access</li><li>Encryption in transit and at rest</li><li>Append-only/tamper-evident auditing</li><li>Secure client messaging infrastructure</li><li>Retention and legal-hold controls</li><li>Secrets/key management</li><li>Backups, monitoring, incident response</li><li>Vendor/model data-handling controls</li></ul></div><div class="card c12"><h3>Control principle</h3><p class="metric" style="font-size:24px">AI identifies. Human decides. The system records both.</p></div></div>`}
function survey(){return `<div class="kicker">Product research</div><h2>Attorney workflow validation</h2><p class="muted">3–5 minute research survey. This is not legal intake.</p><form onsubmit="submitSurvey(event)"><label>Role</label><select name="role"><option>Public defender</option><option>Private criminal defense</option><option>Prosecutor</option><option>Appellate attorney</option><option>Other</option></select><label>Practice area</label><input name="practice"><label>Firm / office size</label><input name="size"><label>Years of experience</label><input name="years"><label>Where does case-review time disappear?</label><textarea name="time"></textarea><label>What repeatedly gets missed or found late?</label><textarea name="missed"></textarea><label>Which CaseBrief capabilities would matter most?</label><textarea name="top"></textarea><button class="btn primary">Save demo response</button></form><div id="surveyMsg"></div>`}
function submitSurvey(e){e.preventDefault();const vals=Object.fromEntries(new FormData(e.target));const arr=JSON.parse(localStorage.getItem('casebrief_survey')||'[]');arr.push(vals);localStorage.setItem('casebrief_survey',JSON.stringify(arr));record('survey.saved','attorney-survey',{responseContentExcluded:true});document.getElementById('surveyMsg').innerHTML='<p class="callout">Saved locally in this browser.</p>';e.target.reset()}
