const {chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>localStorage.clear());
 await page.goto('http://127.0.0.1:8765');
 await page.getByRole('button',{name:'Open demo workspace'}).click();
 const before=await page.evaluate(()=>score());
 await page.locator('.orb').hover();
 const hoverOpacity=await page.locator('.crihover').evaluate(el=>getComputedStyle(el).opacity);
 if(hoverOpacity!=='1')throw Error('CRI circular hover overlay did not reveal');
 await page.getByText('potential rights violation',{exact:true}).waitFor();
 await page.locator('.orb').click();
 await page.getByRole('heading',{name:'Case Readiness Index (CRI)'}).waitFor();
 await page.keyboard.press('Escape');
 await page.evaluate(()=>openDetail('issue','rights-1'));
 await page.getByRole('button',{name:'Mark reviewed',exact:true}).click();
 await page.locator('#decisionReason').fill('Compared doc-1 and doc-8; production remains unconfirmed.');
 await page.getByRole('button',{name:'Save decision'}).click();
 if(await page.evaluate(()=>score())!==before)throw Error('Review incorrectly improves CRI');
 await page.evaluate(()=>openDetail('issue','rights-1'));
 await page.getByRole('button',{name:'Dismiss',exact:true}).click();
 await page.locator('#decisionReason').fill('Synthetic test decision with <script>unsafe</script> text.');
 await page.getByRole('button',{name:'Save decision'}).click();
 if(await page.evaluate(()=>score())!==before+8)throw Error('Dismiss did not update CRI');
 const scriptsBefore=await page.locator('script').count();
 await page.getByRole('button',{name:'Activity History',exact:true}).click();
 await page.getByText('issue.status_changed',{exact:true}).first().waitFor();
 if(await page.locator('script').count()!==scriptsBefore)throw Error('Unsafe activity rendering created executable markup');
 await page.getByRole('button',{name:'AI Assistant',exact:true}).click();
 await page.locator('#aiPrompt').fill('What needs attention next?');
 await page.getByRole('button',{name:'Ask CaseBrief AI',exact:true}).last().click();
 await page.getByText(/Immediate attention should go to/).waitFor();
 await page.getByRole('button',{name:'Drafting Studio',exact:true}).click();
 await page.selectOption('#draftType','discovery_followup');
 await page.getByRole('button',{name:'Generate formatted draft',exact:true}).click();
 await page.getByRole('heading',{name:'Discovery Follow-Up — Draft'}).waitFor();
 await page.getByRole('button',{name:'Communications',exact:true}).click();
 await page.getByRole('heading',{name:'Client & team communications'}).waitFor();
 await page.getByRole('button',{name:'Law & Authority',exact:true}).click();
 await page.getByRole('heading',{name:'Case-linked authority'}).waitFor();
 await page.getByText('Brady v. Maryland',{exact:true}).first().waitFor();
 await page.getByRole('button',{name:'Court + Chronology',exact:true}).click();
 await page.getByText('Motions',{exact:true}).first().waitFor();
 await page.selectOption('#casePicker','matter-002');
 await page.getByRole('heading',{name:'CRI pending'}).waitFor();
 await page.selectOption('#casePicker','matter-001');
 await page.reload();
 if(await page.evaluate(()=>data.issues.find(x=>x.id==='rights-1').status)!=='dismissed')throw Error('State lost');
 for(const v of ['dashboard','review','timeline','evidence','witnesses','documents','authorities','assistant','drafting','communications','umg','audit','safeguards','survey'])await page.evaluate(v=>showView(v),v);
 await page.evaluate(()=>{showView('umg');runConsistency()});
 await page.evaluate(()=>showView('dashboard'));
 await page.setViewportSize({width:390,height:844});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');
 if(errors.length)throw Error(errors.join('\n'));
 console.log('PASS: CRI circular hover/category totals, scoring, safe audit history, AI, drafting, communications, authority, procedural timeline, case switching, persistence, all views, UMG logging, mobile width; no browser errors.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
