const assert=require('node:assert/strict');
const fs=require('node:fs');
const boot=require('./helpers/application.cjs');
const fixture=require('../integration/fixtures/idaho-pretrial.json');
const {run,get,stored}=boot();
assert.equal(run('JSON.stringify(INVESTOR_PILOT_SEED)'),JSON.stringify(fixture.appState),'the presentation seed matches the tested pilot');
assert.equal(run('openInvestorPilot()'),true);
assert.equal(run('data.matter.id'),'SYN-ID-PRETRIAL-001');
assert.equal(run('score()'),63);
assert.equal(run('Object.keys(workspace.cases).length'),3);
assert.equal(run('startInvestorTour()'),true);
assert.match(get('app').innerHTML,/Guided demo/);
assert.equal(run('moveInvestorTour(99)'),false);
assert.equal(run('moveInvestorTour(3)'),true);
const missing=run("simulateAI('What is missing?')");
assert.match(missing.text,/LAB-E02|CUSTODY-E01/);
assert.ok(missing.sources.includes('S04'));
assert.doesNotMatch(missing.text,/Jordan Hale|BC-1841-A|August 26/);
assert.equal(run('generatePilotReviewMemo()'),true);
assert.equal(run('data.drafts.at(-1).filingReady'),false);
assert.match(run('data.drafts.at(-1).body'),/NOT A COURT FILING/);
assert.equal(run('workspace.cases["matter-001"].drafts.length'),0);
run('createPilotShareGrant(["S01","S06"])');
assert.equal(run('JSON.stringify(data.shareGrant.releasedSourceIds)'),JSON.stringify(['S01']));
run('previewPilotFamilyBrief()');
assert.match(get('detailRoot').innerHTML,/Incident report/);
assert.doesNotMatch(get('detailRoot').innerHTML,/Restricted attorney work note|Internal strategy note/);
run('activeSecurityProfile="client";render()');
assert.doesNotMatch(get('app').innerHTML,/SOURCE ANCHORS|Generate internal review memo|Saved drafts/);
for(const view of ['timeline','evidence','witnesses']){run(`showView('${view}')`);assert.doesNotMatch(get('app').innerHTML,/door opening|Taylor Reed|Internal strategy note/)}
run("openDetail('document','S01')");assert.doesNotMatch(get('detailRoot').innerHTML,/Linked review items|Confirm|Mark reviewed/);
assert.equal(run("openDetail('witness','W01')"),false);
assert.equal(run('generatePilotReviewMemo()'),false);
assert.equal(run('startInvestorTour()'),false);
assert.equal(run('requestPilotDemoReset()'),false);
run('activeSecurityProfile="attorney";sessionLocked=true');
assert.equal(run('openPilotFamilyAccess()'),false);
assert.equal(run('generatePilotReviewMemo()'),false);
run('sessionLocked=false;privacyMode=true');
assert.equal(run('startInvestorTour()'),false);
run('privacyMode=false;investorStep=null;current="dashboard";revokePilotShareGrant("test")');
run('previewPilotFamilyBrief()');
assert.match(get('detailRoot').innerHTML,/No sources are currently released/);
const before=JSON.parse(stored()).events.length;
run('requestPilotDemoReset()');
get('confirmSensitive').onclick();
assert.equal(run('score()'),63);
assert.equal(run('data.drafts.length'),0);
assert.equal(run('activePilotShareGrant()'),null);
assert.ok(JSON.parse(stored()).events.length>before);
assert.equal(run('Object.keys(workspace.cases).length'),3);
assert.match(fs.readFileSync('index.html','utf8'),/investor-demo\.js\?v=/);
console.log('PASS investor demo: fixture parity, entry, tour, permissions, targeted sources, internal memo, restricted release, revocation, lock/privacy and scoped reset with history retained.');
