const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{webcrypto}=require('node:crypto');
const elements=new Map();
const classList={toggle(){},add(){},remove(){},contains(){return false}};
const get=id=>{if(!elements.has(id))elements.set(id,{innerHTML:'',textContent:'',value:'',hidden:false,className:'',classList,isConnected:true,focus(){},before(){},appendChild(){},click(){},reset(){}});return elements.get(id)};
const memory=new Map();
const sessionMemory=new Map();
const context={structuredClone,crypto:webcrypto,console,Blob,URL,setTimeout,clearTimeout,setInterval(){return 1},clearInterval(){},alert(){},navigator:{clipboard:{writeText:async()=>{}}},localStorage:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,String(v)),removeItem:k=>memory.delete(k),clear:()=>memory.clear()},sessionStorage:{getItem:k=>sessionMemory.get(k)||null,setItem:(k,v)=>sessionMemory.set(k,String(v)),removeItem:k=>sessionMemory.delete(k),clear:()=>sessionMemory.clear()},document:{body:{classList,appendChild(){}},getElementById:get,querySelector:s=>s==='[role=dialog] button'?get('dialogButton'):s==='.layout'?get('layout'):null,querySelectorAll:()=>[],createElement:()=>get('created'),addEventListener(){},activeElement:null},window:{addEventListener(){}}};
vm.createContext(context);
const html=fs.readFileSync('index.html','utf8');
const sources=[...html.matchAll(/<script src="([^"]+)"/g)].map(m=>m[1].split('?')[0]);
assert.deepEqual(sources,['seed.js','security.js','core.js','views-matter.js','views-work.js','views-comm.js','views-system.js','actions.js','security-runtime.js','demo-capabilities.js']);
for(const src of sources)vm.runInContext(fs.readFileSync(src,'utf8'),context,{filename:src});
const run=s=>vm.runInContext(s,context);
assert.equal(run('current'),'landing');
assert.equal(run('score()'),26);
assert.ok(run('dashboard()').includes('Factors reducing CRI'));
assert.ok(run('dashboard()').includes('Ask AI'));
assert.ok(run('dashboard()').includes('Law & authority'));
assert.ok(run('dashboard()').includes('Where this case is now'));
assert.ok(run('authorities()').includes('Brady v. Maryland'));
assert.ok(run('communications()').includes('Client & team communications'));
assert.ok(run('drafting()').includes('Drafting Studio'));
assert.ok(run("simulateAI('What needs attention next?').text").includes('Immediate attention'));
const narrativeText=String(run("simulateAI('Give me a narrative overview of this case.').text"));assert.ok(narrativeText.length>2500);assert.match(narrativeText,/events that led to State v. Jordan Hale began/);assert.match(narrativeText,/does not establish why Officer Rowan Pike first approached or stopped/);assert.match(narrativeText,/As of the current query/);
get('aiPrompt').value='Give me a complete narrative overview of this case from the beginning.';const draftCountBefore=run('data.drafts.length');run("askAI({preventDefault(){}})");assert.equal(run('data.drafts.length'),draftCountBefore);assert.ok(run("data.assistantMessages.at(-1).text").includes('events that led to State v. Jordan Hale began'));
assert.ok(run('drafting()').includes('Motion to Suppress — full draft'));
get('draftType').value='motion_to_suppress';get('draftInstruction').value='Preserve neutral language.';run("generateDraft({preventDefault(){}})");assert.equal(run("data.drafts.at(-1).type"),'motion_to_suppress');assert.ok(run("data.drafts.at(-1).body").includes('DEFENDANT’S MOTION TO SUPPRESS EVIDENCE'));assert.ok(run("data.drafts.at(-1).body").includes('RELIEF REQUESTED'));
assert.equal(run("data.drafts.at(-1).filingReady"),true);assert.ok(run("data.drafts.at(-1).body").includes('CERTIFICATE OF SERVICE'));assert.ok(run("data.drafts.at(-1).body").includes('PROPOSED ORDER'));assert.ok(run("data.drafts.at(-1).body").includes('/s/ Avery Chen'));assert.ok(!run("data.drafts.at(-1).body").includes('[INSERT'));
for(const type of Object.keys(run('LEGAL_DRAFT_CATALOG'))){const d=run(`createCatalogDraft('${type}','Automated document validation.','test')`);assert.equal(d.type,type);assert.ok(d.body.length>350,`${type} too short`)}
assert.equal(run("filingReadiness('motion_to_compel').ready"),true);assert.equal(run("filingReadiness('notice_of_appeal').ready"),false);
run('delete data.matter.filingProfile');assert.equal(run("filingReadiness('motion_to_suppress').ready"),true);assert.ok(run("motionToSuppressText()").includes('/s/ Avery Chen'));run('data.matter.filingProfile=structuredClone(primarySeed.matter.filingProfile)');
const editableId=run("data.drafts.find(d=>d.type==='motion_to_suppress').id");run(`openDraft('${editableId}')`);run(`beginDraftEdit('${editableId}')`);get('draftEditor').value='Revised attorney text <script>must remain plain text</script>';run(`saveDraftEdits('${editableId}')`);assert.equal(run(`data.drafts.find(d=>d.id==='${editableId}').versions.length`),1);assert.ok(run(`data.drafts.find(d=>d.id==='${editableId}').body`).includes('<script>must remain plain text</script>'));assert.ok(get('detailRoot').innerHTML.includes('&lt;script&gt;must remain plain text&lt;/script&gt;'));assert.ok(run("workspace.events.some(e=>e.action==='draft.version_saved'&&e.details.contentExcludedFromAudit)"));
assert.ok(run('activityHistory()').includes('Document version saved'));assert.ok(run('activityHistory()').includes('Current character count'));
run("beginIssueDecision('rights-1','reviewed')");get('decisionReason').value=' ';run("saveIssueDecision({preventDefault(){}},'rights-1','reviewed')");assert.equal(run("data.issues.find(x=>x.id==='rights-1').status"),'open');
get('decisionReason').value='Compared doc-1 and doc-8; unresolved.';run("saveIssueDecision({preventDefault(){}},'rights-1','reviewed')");assert.equal(run('score()'),26);
run("beginIssueDecision('rights-1','dismissed')");get('decisionReason').value='<script>unsafe</script>';run("saveIssueDecision({preventDefault(){}},'rights-1','dismissed')");assert.equal(run('score()'),34);assert.ok(run('activityHistory()').includes('&lt;script&gt;unsafe&lt;/script&gt;'));assert.ok(run('activityHistory()').includes('Review status changed'));assert.ok(!run('activityHistory()').includes('<td><pre>'));
assert.equal(run("workspace.events.filter(e=>e.action==='issue.status_changed').length"),2);
run("switchCase('matter-002')");assert.ok(run('dashboard()').includes('CRI pending'));assert.equal(run('data.documents.length'),0);run("switchCase('matter-001')");assert.equal(run('score()'),34);
for(const view of ['landing','dashboard','review','timeline','evidence','witnesses','documents','authorities','assistant','drafting','communications','umg','audit','safeguards','survey'])run(`showView('${view}')`);
run("showView('umg');runConsistency()");assert.ok(run("workspace.events.some(e=>e.action==='analysis.completed'&&e.actor.type==='system')"));
assert.equal(JSON.parse(memory.get('casebrief_workspace_v3')).cases['matter-001'].issues.find(x=>x.id==='rights-1').status,'dismissed');
context.localStorage.setItem=()=>{throw Error('quota')};run("record('test.storage_failure','test')");assert.equal(run('storageOK'),false);
console.log('PASS: modular script execution, v3 views, CRI categories, AI/drafting/comms/authority surfaces, required reasons, reviewed/dismissed scoring, escaped history, case isolation, saved v3 state, system analysis events, storage failure notice.');
